apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-cal-deployment
  labels:
    app: flask-cal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-cal
  template:
    metadata:
      labels:
        app: flask-cal
    spec:
      containers:
      - name: flask-cal
        image: nagendra206/flask_cal:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-cal-service
spec:
  selector:
    app: flask-cal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
